services:
  fraud-detection:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-detection-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./model:/app/model
      - ./outputs:/app/outputs
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    stdin_open: true
    tty: true
    restart: unless-stopped
